# enable vi mode 
setw -g mode-keys vi

# enable mouse mode
set -g mouse on

# use C-a as secondary prefix key
set -g prefix2 C-a
bind C-a send-prefix -2

# set windows and panes to base 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# improve colors
set -g default-terminal "${TERM}"
set -as terminal-features ",*:RGB"

# configure status bar
set -g status-style "bg=default"
set -g status-left "#(whoami) "
set -g status-right " "
# set -g status-right "#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)"

# increase history
set -g history-limit 10000

# enable hot reloading
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# list of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-yank"

# tmux plugin manager
run "~/.tmux/plugins/tpm/tpm"
