# Backend
backend = "glx";
vsync = true;
xrender-sync-fence = true; 

# Rounded corners
corner-radius = 10;
rounded-corners-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dmenu'",
];

# Shadows
shadow = true;
shadow-radius = 5
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.8;
shadow-color = "#000000"
shadow-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dmenu'",
];

# Window rules
# https://github.com/orgs/regolith-linux/discussions/949
wintypes:
{
	tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
 	dock = { shadow = false; clip-shadow-above = true; }
 	dnd = { shadow = false; }
 	menu = { shadow = false; }
 	popup_menu = { opacity = 0.8; }
 	dropdown_menu = { opacity = 0.8; }
};

# Attempt to migrate to new Window Rules
# rules: ({
#  	match = "window_type = 'tooltip'";
# 	fade = true;
#    	shadow = true;
#   	full-shadow = false;
# 	opacity = 0.75;
# }, {
# 	match = "window_type = 'dock'";
# 	shadow = false;
# 	clip-shadow-above = true;
# }, {
# 	match = "window_type = 'dnd' || "
# 		"window_type = 'menu'";
# 	shadow = false;
# }, {
# 	match = "window_type = 'popup_menu' || "
# 		"window_type = 'dropdown_menu'";
# 	opacity = 0.8;
# })
