"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[username]
format = "[\u25D6](black)[$user](bg:black)"
show_always = true

[hostname]
format = "[@$hostname](bg:black)[\u25D7](black) "
ssh_only = false

[character]
success_symbol = "[\u276F](white)"
error_symbol = "[\u276F](red)"

[directory]
format = "[$path](white) "

[git_branch]
format = "[$branch](purple) "

[git_status]
format = "[$all_status$ahead_behind](red)"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
