"$schema" = 'https://starship.rs/config-schema.json'

format = """
$character\
$username\
$hostname\
[:](white)\
$directory\
$git_branch\
$git_status\
[ % ](white)"""

[username]
format = "[$user](white)"
show_always = true

[hostname]
format = "[@$hostname](white)"
ssh_only = true

[character]
success_symbol = "[\u25CB](white)"
error_symbol = "[\u25CB](red)"

[directory]
format = " [$path](white)"

[git_branch]
format = " [$branch](purple)"

[git_status]
format = " [$all_status$ahead_behind](red)"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
