[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2" #"#a89984"

[colors.normal]
black	= "#1F1F1F"
red		= "#ea6962"
green   = "#a9b665" # vscPink
yellow  = "#DCDCAA"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#7daea3"
white	= "#ebdbb2"
