live_config_reload = true

# RASMUS COLORSCHEME
[colors.primary]
background = '#1a1a19'
foreground = '#d1d1d1'

[colors.cursor]
text       = '#1a1a19'
cursor     = '#d1d1d1'

[colors.normal]
black      = '#333332'
red        = '#ff968c'
green      = '#61957f'
yellow     = '#ffc591'
blue       = '#8db4d4'
magenta    = '#de9bc8'
cyan       = '#7bb099'
white      = '#d1d1d1'

[colors.bright]
black      = '#4c4c4b'
red        = '#ffafa5'
green      = '#7aae98'
yellow     ='#ffdeaa'
blue       = '#a6cded'
magenta    = '#f7b4e1'
cyan       = '#94c9b2'
white      = '#eaeaea'

# DARK PLUS COLORSCHEME
# [colors.primary]
# background = '#1F1F1F'
# foreground = '#D4D4D4'

# [colors.cursor]
# text       = "#1F1F1F"
# cursor     = "#D4D4D4"

# [colors.normal]
# black      = "#1F1F1F" 
# red        = "#F44747"
# green      = "#6A9955"
# yellow     = "#795E26"
# blue       = "#007ACC"
# magenta    = "#C586C0"
# cyan       = "#4FC1FF"
# white      = "#D4D4D4"

# [colors.bright]
# black      = "#808080"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "full"
option_as_alt = "both"
# opacity = 0.5
# blur = true

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 8
y = 4
