theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode", 
  "version-control",
  "read-only-indicator",
  "file-name", 
  "file-modification-indicator", 
]
right = [ 
  "diagnostics",
  "position",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
"y" = ["yank", "yank_to_clipboard"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.normal."["]
"[" = "goto_file_start"

[keys.normal."]"]
"]" = "goto_file_end"

[keys.select]
"y" = ["yank", "yank_to_clipboard"]
