[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
pyright = { command = "pyright-langserver", args = ["--stdio"] }
ruff = { command = "ruff-lsp" }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
language-servers = [ { name = "pyright", except-features = [ "format", "diagnostics" ] }, "ruff" ]
formatter = { command = "ruff", args = ["format", "--line-length=200", "--quiet", "-"] }
auto-format = true
